Update pretty.yml

diff --git a/.github/workflows/pretty.yml b/.github/workflows/pretty.yml
--- a/.github/workflows/pretty.yml
+++ b/.github/workflows/pretty.yml
@@ -1,24 +1,109 @@
-name: Ready for deployment
+name: Publishing ready
 on: [push, pull_request]
 jobs:
-
   build:
     name: Build
     runs-on: ubuntu-18.04
-    strategy:
-      matrix:
-        singularity_version:
-          - '3.7.3'
-    container:
-      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
-      options: --privileged
     steps:
-    - name: Check if README.md exists
+    - name: Check out code
+      uses: actions/checkout@v2
+      
+    - name: Install useful utilities
+      run: sudo apt-get install -y tree
+
+    - name: Checking if LICENSE exists
       run: |
-      if [ -f README.md ]; then
-        echo "File README.md exists in repository."
-        exit 0
-      else
-        echo "File README.md does exist in repository."
-        exit 1
-      fi
+        FILE=LICENSE
+        if [ -f "$FILE" ]; then
+            echo "File "$FILE" exists."
+            exit 0
+        else 
+            echo "File $FILE does not exist."
+            exit 1
+        fi
+
+    - name: Checking if Apache License Version 2.0, January 2004 is being used
+      run: |
+        if grep --quiet "Apache License" LICENSE && grep --quiet "Version 2.0, January 2004" LICENSE; then
+            echo "Using Apache License Version 2.0, January 2004"
+            exit 0
+        else
+            echo "Not using Apache License Version 2.0, January 2004"
+            exit 1
+        fi
+    
+    - name: Checking if CONTRIBUTING guide exists
+      run: |
+        FILE=CONTRIBUTING.md
+        if [ -f "$FILE" ]; then
+            echo "File "$FILE" exists."
+            exit 0
+        else 
+            echo "File $FILE does not exist."
+            exit 1
+        fi
+
+    - name: Checking if README file exists
+      run: |
+        FILE=README.md
+        if [ -f "$FILE" ]; then
+            echo "File "$FILE" exists."
+            exit 0
+        else 
+            echo "File $FILE does not exist."
+            exit 1
+        fi
+    
+    - name: Checking if copyrighted to Pittsburgh Supercomputing Center
+      run: |
+        if grep --quiet "Pittsburgh Supercomputing Center. All Rights Reserved." README.md; then
+            echo "Copyright (c) Pittsburgh Supercomputing Center"
+            exit 0
+        else
+            echo "No reference to Pittsburgh Supercomputing Center"
+            exit 1
+        fi
+
+    - name: Checking if there exists at least one Singularity definition file
+      run: |
+        FILE=Singularity
+        if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
+            echo "File "$FILE" was found.";
+            exit 0 
+        else 
+            echo "File "$FILE" was not found.";
+            exit 1
+        fi
+
+    - name: Checking if there exists at least one build script
+      run: |
+        FILE=build.sh
+        if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
+            echo "File "$FILE" was found.";
+            exit 0 
+        else 
+            echo "File "$FILE" was not found.";
+            exit 1
+        fi
+
+    - name: Checking if there exists at least one remote build script
+      run: |
+        FILE=rbuild.sh
+        if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
+            echo "File "$FILE" was found.";
+            exit 0 
+        else 
+            echo "File "$FILE" was not found.";
+            exit 1
+        fi
+
+    - name: Checking if there exists at least one test script
+      run: |
+        FILE=test.sh
+        if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
+            echo "File "$FILE" was found.";
+            exit 0 
+        else 
+            echo "File "$FILE" was not found.";
+            exit 1
+        fi
